name: Manual Run Data(subset) Pipeline

on: workflow_dispatch

jobs:
  authorization:
    runs-on: ubuntu-latest
    steps:
    - name: Authorization check
      uses: octokit/request-action@v2.0.0
      with:
        route: GET /repos/:repository/collaborators/${{ github.actor }}
        repository: ${{ github.repository }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}